version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: salessavvy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salessavvy
    ports:
      - "3306:3306"

  backend:
    build: .
    container_name: salessavvy-backend
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/salessavvy
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 9090
    depends_on:
      - mysql
